

export interface Cfgs
{

    storeAml: boolean,
    subStoreAml: boolean,
    sccHashmapNamespaces: boolean,
    dashmapNamespaces: boolean,
    allTypes: boolean,
    boolType: boolean,
    charType: boolean,
    f32Type: boolean,
    f64Type: boolean,
    i8Type: boolean,
    i16Type: boolean,
    i32Type: boolean,
    i64Type: boolean,
    i128Type: boolean,
    isizeType: boolean,
    stringType: boolean,
    u8Type: boolean,
    u16Type: boolean,
    u32Type: boolean,
    u64Type: boolean,
    u128Type: boolean,
    usizeType: boolean,
    whateverType: boolean,
    selectedTypeType: boolean,
    vecBoolType: boolean,
    vecCharType: boolean,
    vecF32Type: boolean,
    vecF64Type: boolean,
    vecI8Type: boolean,
    vecI16Type: boolean,
    vecI32Type: boolean,
    vecI64Type: boolean,
    vecI128Type: boolean,
    vecIsizeType: boolean,
    vecU8Type: boolean,
    vecU16Type: boolean,
    vecU32Type: boolean,
    vecU64Type: boolean,
    vecU128Type: boolean,
    vecUsizeType: boolean,
    vecStringType: boolean,
    vecWhateverType: boolean,
    vecSelectedType: boolean,
    allKeyTypesString: boolean,
    allKeyTypesArcString: boolean,
    
    /*
    boolKeyTypeString: boolean,
    boolKeyTypeArcString: boolean,
    charKeyTypeString: boolean,
    charKeyTypeArcString: boolean,
    f32KeyTypeString: boolean,
    f32KeyTypeArcString: boolean,
    f64KeyTypeString: boolean,
    f64KeyTypeArcString: boolean,
    i8KeyTypeString: boolean,
    i8KeyTypeArcString: boolean,
    i16KeyTypeString: boolean,
    i16KeyTypeArcString: boolean,
    i32KeyTypeString: boolean,
    i32KeyTypeArcString: boolean,
    i64KeyTypeString: boolean,
    i64KeyTypeArcString: boolean,
    i128KeyTypeString: boolean,
    i128KeyTypeArcString: boolean,
    isizeKeyTypeString: boolean,
    isizeKeyTypeArcString: boolean,
    selectedRypeKeyTypeString: boolean,
    selectedTypeKeyTypeArcString: boolean,
    stringKeyTypeString: boolean,
    stringKeyTypeArcString: boolean,
    u8KeyTypeString: boolean,
    u8KeyTypeArcString: boolean,
    u16KeyTypeString: boolean,
    u16KeyTypeArcString: boolean,
    u32KeyTypeString: boolean,
    u32KeyTypeArcString: boolean,
    u64KeyTypeString: boolean,
    u64KeyTypeArcString: boolean,
    u128KeyTypeString: boolean,
    u128KeyTypeArcString: boolean,
    usizeKeyTypeString: boolean,
    usizeKeyTypeArcString: boolean,
    whateverKeyTypeString: boolean,
    whateverKeyTypeArcString: boolean
    */

}

//selectedTypeIoType: boolean,

export function defaultCfgs(): Cfgs
{

    return {

        storeAml: false,
        subStoreAml: false,
        sccHashmapNamespaces: false,
        dashmapNamespaces: false,
        allTypes: false,
        boolType: false,
        charType: false,
        f32Type: false,
        f64Type: false,
        i8Type: false,
        i16Type: false,
        i32Type: false,
        i64Type: false,
        i128Type: false,
        isizeType: false,
        stringType: false,
        u8Type: false,
        u16Type: false,
        u32Type: false,
        u64Type: false,
        u128Type: false,
        usizeType: false,
        whateverType: false,
        selectedTypeType: false,
        vecBoolType: false,
        vecCharType: false,
        vecF32Type: false,
        vecF64Type: false,
        vecI8Type: false,
        vecI16Type: false,
        vecI32Type: false,
        vecI64Type: false,
        vecI128Type: false,
        vecIsizeType: false,
        vecU8Type: false,
        vecU16Type: false,
        vecU32Type: false,
        vecU64Type: false,
        vecU128Type: false,
        vecUsizeType: false,
        vecStringType: false,
        vecWhateverType: false,
        vecSelectedType: false,
        allKeyTypesString: false,
        allKeyTypesArcString: false,

        /*
        boolKeyTypeString: false,
        boolKeyTypeArcString: false,
        charKeyTypeString: false,
        charKeyTypeArcString: false,
        f32KeyTypeString: false,
        f32KeyTypeArcString: false,
        f64KeyTypeString: false,
        f64KeyTypeArcString: false,
        i8KeyTypeString: false,
        i8KeyTypeArcString: false,
        i16KeyTypeString: false,
        i16KeyTypeArcString: false,
        i32KeyTypeString: false,
        i32KeyTypeArcString: false,
        i64KeyTypeString: false,
        i64KeyTypeArcString: false,
        i128KeyTypeString: false,
        i128KeyTypeArcString: false,
        isizeKeyTypeString: false,
        isizeKeyTypeArcString: false,
        selectedRypeKeyTypeString: false,
        selectedTypeKeyTypeArcString: false,
        stringKeyTypeString: false,
        stringKeyTypeArcString: false,
        u8KeyTypeString: false,
        u8KeyTypeArcString: false,
        u16KeyTypeString: false,
        u16KeyTypeArcString: false,
        u32KeyTypeString: false,
        u32KeyTypeArcString: false,
        u64KeyTypeString: false,
        u64KeyTypeArcString: false,
        u128KeyTypeString: false,
        u128KeyTypeArcString: false,
        usizeKeyTypeString: false,
        usizeKeyTypeArcString: false,
        whateverKeyTypeString: false,
        whateverKeyTypeArcString: false
        */
    
    }

    //selectedTypeIoType: false,

}


